[package]
name = "plotter"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-rs = { version = "0.20.1", features = ["svg"] }
gtk = { version = "0.9.1", package = "gtk4", features = ["v4_14"] }
rand = "0.8.5"

